// <auto-generated />
using System;
using APIRESTfulNUXIBA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIRESTfulNUXIBA.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250525224101_Primera Migracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIRESTfulNUXIBA.Entities.Area", b =>
                {
                    b.Property<int>("IDArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDArea"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusArea")
                        .HasColumnType("int");

                    b.HasKey("IDArea");

                    b.ToTable("ccRIACat_Areas", (string)null);
                });

            modelBuilder.Entity("APIRESTfulNUXIBA.Entities.Login", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logId"));

                    b.Property<int>("Extension")
                        .HasColumnType("int");

                    b.Property<int>("TipoMov")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("logId");

                    b.HasIndex("User_id");

                    b.ToTable("ccloglogin", (string)null);
                });

            modelBuilder.Entity("APIRESTfulNUXIBA.Entities.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDArea")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLoginAttempt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoUser_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fCreate")
                        .HasColumnType("datetime2");

                    b.HasKey("User_id");

                    b.HasIndex("IDArea");

                    b.ToTable("ccUsers", (string)null);
                });

            modelBuilder.Entity("APIRESTfulNUXIBA.Entities.Login", b =>
                {
                    b.HasOne("APIRESTfulNUXIBA.Entities.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIRESTfulNUXIBA.Entities.User", b =>
                {
                    b.HasOne("APIRESTfulNUXIBA.Entities.Area", "Area")
                        .WithMany("Users")
                        .HasForeignKey("IDArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("APIRESTfulNUXIBA.Entities.Area", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("APIRESTfulNUXIBA.Entities.User", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
